### ISSUE TITLE
Need help regarding adding packages in tikzjax

### ISSUE THREAD

**Issue by ravirathore** [ravirathore/tikzjax#1]
@drgrice1
 
Hi, Thanks for sharing tikzjax. Its a very interesting project.

I request your help please regarding few things :-

1. I compiled your repository and successfully ran it (ww-modifications branch).
2. I want to add few packages in it e.g. chemfig etc.
3. For adding new packages, in your 'Options' section, you have mentioned to add packages like this:

"Additional packages can be made available by adding a file <package-name>.json that contains an array of file names needed by the package to the tex_packages directory, and adding the gzipped files in that array to the tex_files directory."

3.1 Does this mean this:

	3.1.1 Create new directory 'tex_packages'
	3.1.2 Create chemfig.json file in it with the content (in array format):
			3.1.2.1 [ "chemfig.sty", "chemfig.tex" ]
	3.1.3 Create tex_files directory with 2 files: chemfig.tex.gz, chemfig.sty.gz
	3.1.4 Execute: npm run build
	3.1.5 Do we also have to include above 2 filenames in the file: tex_files.json ?

Request your guidance please.

Thanks,

**Comment by drgrice1** [comment]
It seems that I changed that way that works, and did not update the README.md file.  Then I gave up on the concept of tikzjax.  If I recall, you need to add the needed files to `tex_files.json` and then run `genTexFiles.js`.  That will attempt to locate the files for the package using kpsewhich, and if found will compress them and put them where they need to be.

**Comment by drgrice1** [comment]
By the way, I gave up on the concept of tikzjax because I highly doubt that it will work in production for what I was looking for.  At least not in the near future.  I was looking for graphical image generation for the open source online homework system WeBWorK.  The problem is that LaTeX in general is to computationally intensive to run in the browser on the common range of devices that are out there today.  Not to mention that web assembly itself is still in its infancy and many devices still don't fully support it, or at least not well.

**Comment by ravirathore** [comment]
@drgrice1 
Thanks for the revert. I included those 2 files(of chemfig) in tex_files.json and compiled. Compilation copied all required files in tex_files directory.
Results are hosted here: https://github.com/ravirathore/newchem2

And, tried to run following code:

<script type="text/tikz" data-show-console="true" data-tex-packages="" data-tex-package='{"chemfig":""}'>
  
    \chemfig{A-B}
  
    </script>

But, it gave following errors:

This is e-TeX, Version 3.14159265-2.6 (preloaded format=latex 2021.2.6)
tikzjax.js:1 **entering extended mode
tikzjax.js:1 (input.tex
tikzjax.js:1 LaTeX2e <2020-02-02> patch level 2
tikzjax.js:1 No file input.aux.
tikzjax.js:1 ABD: EveryShipout initializing macros
tikzjax.js:1 ! Undefined control sequence.
tikzjax.js:1 l.3     \chemfig
tikzjax.js:1                 {A-B}
tikzjax.js:1 ? Type <return> to proceed, S to scroll future error messages,
tikzjax.js:1 R to run without stopping, Q to run quietly,
tikzjax.js:1 I to insert something, E to edit your file,
tikzjax.js:1 1 or ... or 9 to ignore the next 1 to 9 tokens of input,
tikzjax.js:1 H for help, X to quit.
tikzjax.js:1 ? 
tikzjax.js:1 ! Emergency stop.
tikzjax.js:1 l.3     \chemfig
tikzjax.js:1                 {A-B}
tikzjax.js:1 Error: Could not find file input.dvi
    at Me (run-tex.js:1:412407)
    at texify (run-tex.js:1:417762)

Please advise, where am I making mistake?

Also, this project has good future, because:-
1. It opens scope for offline usage in browsers.
2. Chips are getting faster and cheaper; and lot of browsers available now on Android etc.
3. Along with porting the softwares, you can try porting the compiler itself to webassembly(e.g. Pascal). Will save a lot of efforts and time.
4. Heavy softwares like gaming engines can be ported, which might need lot of data bandwidth if hosted on servers.

Thanks,
